services:
  my-springboot-health:
    image: 992382367281.dkr.ecr.ap-northeast-2.amazonaws.com/springboot:latest
    ports:
      - 8002:8002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      my-mysql:
        condition: service_healthy
      my-redis:
        condition: service_healthy
    restart: unless-stopped  # 실패 시 자동 재시도
        
  my-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: sang0412        # root 비밀번호
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-psang0412"]
      interval: 5s
      retries: 10
      
  my-redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
      
  my-elastic:
    image: 992382367281.dkr.ecr.ap-northeast-2.amazonaws.com/es:latest
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.enabled=false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./dict:/usr/share/elasticsearch/config/dict
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://3.34.45.205:9200 || exit 1"]
      interval: 5s
      retries: 10
      start_period: 20s
  
  my-vue:
    image: 992382367281.dkr.ecr.ap-northeast-2.amazonaws.com/vue:latest
    ports:
      - 8003:8003
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 